# Lightroom 会员解锁（Quantumult X 重写规则）
# 引用远程脚本，配合 [rewrite_remote] 订阅使用
^https:\/\/lcs-mobile-cops\.adobe\.io\/mobiles\/access_profile\/v3 url script-response-body https://raw.githubusercontent.com/chinyinglu/shadowrocket-lightroom/main/qx-lightroom.js
